# Generated by Django 2.0.5 on 2019-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0002_auto_20191202_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=30, verbose_name='课程')),
                ('bb', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='学分')),
                ('cc', models.CharField(max_length=30, verbose_name='类别')),
                ('dd', models.CharField(max_length=30, verbose_name='考核方式')),
                ('ee', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='成绩')),
                ('ff', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='绩点')),
            ],
        ),
    ]
