# Generated by Django 2.0.5 on 2019-12-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='bb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='绩点'),
        ),
    ]
