# Generated by Django 2.0.5 on 2019-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0005_auto_20191202_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='gg',
            field=models.CharField(default='201701811', max_length=12, verbose_name='学号'),
        ),
    ]
