# Generated by Django 2.0.5 on 2019-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0006_class_gg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mima',
            field=models.CharField(default='201701811', max_length=15, verbose_name='密码'),
        ),
    ]
